version: "3.8"

services:
  fastapi.app:
    image: fastapi.app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi.app
    ports:
      - 80:80
